### ISSUE TITLE
Authenticate with several keyhandles

### ISSUE THREAD

**Issue by klali** [Yubico/libu2f-host#10]
The library should have a function that accepts a list of keyhandles for authentication, doing the work to loop through them and send the correct handle to the correct authenticator.

**Comment by azqa** [comment]
You can close this issue. I was passing it all the key handles at the same time. I hope this feature will be integrated in the next release.

**Comment by will** [comment]
I'm not sure how to go forward with several keyhandles. If I just try them one at a time, that's a horrible experience as you have to wait for a timeout on each of them. Unless maybe `u2fh_authenticate/2` is threadsafe?
