### ISSUE TITLE
/bin/bash: gtkdoc-mktmpl: command not found

### ISSUE THREAD

**Issue by perry-amsterdam** [Yubico/libu2f-host#103]
When i try to compile the code, i get the following error:

Makefile:812: recipe for target 'tmpl-build.stamp' failed
make[2]: *** [tmpl-build.stamp] Error 127
make[2]: Leaving directory '/root/libu2f-host/gtk-doc'
Makefile:641: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/libu2f-host'
Makefile:552: recipe for target 'all' failed
make: *** [all] Error 2
root@sheldon-XPS13-9333:~/libu2f-host#

**Comment by a-dma** [comment]
Have installed `gtk-doc-tools`?

**Comment by perry-amsterdam** [comment]
Yes is have :-)

Some more error messages.

make[2]: Entering directory '/root/libu2f-host/gtk-doc'
  DOC   Rebuilding template files
/bin/bash: gtkdoc-mktmpl: command not found
Makefile:812: recipe for target 'tmpl-build.stamp' failed

dpkg-query -L gtk-doc-tools|grep mktmpl
Nothing found.

Package: gtk-doc-tools
Versions: 
1.27-3 

It looks that gtk-doc-tools 1.27-3 does not contains : gtkdoc-mktmpl

**Comment by a-dma** [comment]
Apparently it has been [dropped in 1.26](https://github.com/GNOME/gtk-doc/blob/master/NEWS#L73).

We'll probably end up dropping gtk-doc altogether.

How are you building? Is that a source tarball? A git checkout? Try explicitly adding `--disable-gtk-doc` to `configure`. I removed the package and I can build just fine on Ubuntu.

**Comment by perry-amsterdam** [comment]
I am using a git checkout, it now builds :-)  Where can i find the api documentation if i can not build the documentation ?

**Comment by a-dma** [comment]
I've pushed some changes to a branch called `gtk-doc` that doesn't use mktmpl. Can you have a look if that works fine for you?

**Comment by perry-amsterdam** [comment]
I did the following:

git clone https://github.com/Yubico/libu2f-host.git
cd libu2f-host/
git checkout remotes/origin/gtk-doc
make 

I got the following error message:

  DOC   Building HTML
  DOC   Fixing cross-references
html/u2f-host-u2f-host-types.html:150: warning: no link for: "u2fh-global-init" -> (<code class="function">u2fh_global_init()</code>).
html/u2f-host-u2f-host-types.html:172: warning: no link for: "u2fh-register" -> (<code class="function">u2fh_register()</code>).
html/u2f-host-u2f-host-types.html:172: warning: no link for: "u2fh-authenticate" -> (<code class="function">u2fh_authenticate()</code>).
  DOC   Building PDF
Traceback (most recent call last):
  File "/usr/bin/gtkdoc-mkpdf", line 48, in <module>
    sys.exit(mkpdf.run(options))
  File "/usr/share/gtk-doc/python/gtkdoc/mkpdf.py", line 73, in run
    pc = subprocess.Popen([config.dblatex, '--help'], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Makefile:911: recipe for target 'pdf-build.stamp' failed
make[3]: *** [pdf-build.stamp] Error 1
make[3]: Leaving directory '/root/libu2f-host/gtk-doc'
Makefile:644: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/root/libu2f-host'
Makefile:555: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/root/libu2f-host'
cfg.mk:26: recipe for target 'bootstrap' failed
make: *** [bootstrap] Error 2
root@sheldon-XPS13-9333:~/libu2f-host#

**Comment by a-dma** [comment]
Is your `gtkdoc-mkpdf` working fine?

Try generating only html with `make clean && ./configure --enable-gtk-doc --disable-gtk-doc-pdf --enable-gtk-doc-html && make`. See if that helps.

**Comment by perry-amsterdam** [comment]
Super it works :-)

**Comment by a-dma** [comment]
Cool, then I'll merge that branch and close this issue.
