### ISSUE TITLE
use CommonCrypto instead of gnulib on darwin

### ISSUE THREAD

**Issue by mxswd** [Yubico/libu2f-host#109]
There is no need to use gnulib for sha256_buffer on modern darwin systems.

Cmake should detect the `CommonCrypto/CommonDigest.h` then conditionally use `CC_SHA256` instead.

**Comment by nevun** [comment]
We are archiving this project and closing issues. Please open a new one in the replacement library's repo: https://github.com/Yubico/libfido2 if it is still applicable.
