### ISSUE TITLE
Duplicate Registration of the same device

### ISSUE THREAD

**Issue by sidsatheeesh** [Yubico/libu2f-host#112]
Hi, I have a doubt. I have set a complete solution around the Yubico U2F keys. But now, I cannot stop duplicate registration of the same device for an user for the same app id. While checking on the keyhandles on my database they show different values for each of the duplicate registration. Please help me out.
Is it something related to the high level/low level JavaScript API?

**Comment by Cl1608Ho** [comment]
The way to do it isn't registering and checking key handle on your server (because key handle is derived kind-of randomly at each registration) but sending all your already known keys (/ challenges) for this user ot the U2F key and let the U2F key decide it already knows this key.

**Comment by nevun** [comment]
We are archiving this project and closing issues. Please open a new one in the replacement library's repo: https://github.com/Yubico/libfido2 if it is still applicable.
