### ISSUE TITLE
error in systemd-udevd : Specified group 'plugdev' unknown

### ISSUE THREAD

**Issue by Maryse47** [Yubico/libu2f-host#116]
This is caused by https://github.com/Yubico/libu2f-host/commit/0d6d6ba7164c61d745d960ed3e50775c7659d928 and `plugdev` group which is Debian/Ubuntu specific and doesn't exist in other distros like Fedora/RHEL, Arch or openSUSE. Relying on it is treated as a bug there and should be avoided.

https://bugs.archlinux.org/task/35602
https://bugzilla.redhat.com/show_bug.cgi?id=859244#c2
https://bugzilla.redhat.com/show_bug.cgi?id=859244#c16

**Comment by cmorgenstern** [comment]
Recommended fix is to remove the reference to the plugdev group and mode and add support for legacy systems using `TAG+="udev-acl"`.

See: https://wiki.archlinux.org/index.php/Talk:Udev#Use_of_.27uaccess.27_instead_of_GROUP_and_MODE.3F

**Comment by Maryse47** [comment]
@klali are you going to fix this?

**Comment by klali** [comment]
@nbraud apparently the changes to accomodate non-systemd fail on other distros.

If anyone has opinions on how this should look to work across the maximum amount of distributions I'm open to changing this. IIRC the udev-acl tag breaks down on some versions of debian/ubuntu.

**Comment by Maryse47** [comment]
I would go for reverting https://github.com/Yubico/libu2f-host/commit/0d6d6ba7164c61d745d960ed3e50775c7659d928 and leave non-systemd distros to carry downstream fixes if there in no one-size-fit-all solution.

**Comment by mikijov** [comment]
Would something like this work?
- create two flavours of rules, 70-u2f.rules.plugdev and 70-u2f.rules.users
- change makefile to check build system for existence of 'plugdev' group
- on systems with 'plugdev' group, include 70-u2f.rules.plugdev
- on other systems use 70-u2f.rules.users 

Many apologies for not doing a PR myself. I feel I am stretching my knowledge here.

**Comment by flokli** [comment]
I had some offline discussions about this. Using `plugdev` is wrong conceptionally:

> plugdev: Allows members to mount (only with the options nodev and nosuid, for security reasons) and umount removable devices through pmount. 

This is about block devices (which u2f devices aren't), and most distros don't use pmount these days anymore.

Relying on a group `plugdev` is problematic, it's not guaranteed to exist.

I propose removing the udev rule from here entirely, and let distros carry their downstream distro-specific udev rules (which they already do anyways).

Also note systemd-based distros will work out of the box soon: https://github.com/systemd/systemd/commit/d45ee2f31a8358db0accde2e7c81777cedadc3c2

**Comment by nevun** [comment]
As you say, this is now handled by systemd. Anyways, we are archiving this project and closing issues. Please open a new one in the replacement library's repo: https://github.com/Yubico/libfido2 if there are still open questions we failed to answer.
