### ISSUE TITLE
udev rule for gpg access

### ISSUE THREAD

**Issue by elerch** [Yubico/libu2f-host#125]
When using the udev rules from this project, HID access for u2f works fine, but gpg access is not available to users. I added the following rule to make this work:

```
# Yubico YubiKey: CCID (Smart Card access for gpg)
SUBSYSTEMS=="usb", ATTRS{idVendor}=="1050", ATTRS{idProduct}=="0113|0114|0115|0116|0120|0200|0402|0403|0406|0407|0410", TAG+="uaccess"
```

I see a similar comment in #28. I would issue a PR for this, but given the name of this repo is "libu2f-host", maybe this rule should be in a different repo and/or different file. I couldn't find a suitable alternative repo, however, so I was hoping to get some direction on this, or at least bring to someone's attention that the provided rules seem insufficient for gpg smart card access.

**Comment by klali** [comment]
As you've realised this isn't the place for udev rules for smartcard.

The typical solution on linux is that pcscd handles the smartcard reader through libccid, pcscd is in that case often running as root and doesn't need anything special for permissions.

Gnupg also supports direct access to the reader, on debian they ship a udev file (/lib/udev/rules.d/60-scdaemon.rules) for the required permissions.
