### ISSUE TITLE
Add support device  Active Rutoken u2f

### ISSUE THREAD

**Issue by syaroshevskiy** [Yubico/libu2f-host#128]
Please, add support device Active Rutoken u2f to file: 70-u2f.rules
Manufacturer's website: https://www.rutoken.ru/products/all/rutoken-u2f/

`KERNEL=="hidraw*", SUBSYSTEM=="hidraw", ATTRS{idVendor}=="0a89", ATTRS{idProduct}=="0090", TAG+="uaccess", GROUP="plugdev", MODE="0660"
`

**Comment by klali** [comment]
Please add this as a pull request.
