### ISSUE TITLE
Can't find U2F device on Windows 10 May 2019 Update (1903)

### ISSUE THREAD

**Issue by arlenyan** [Yubico/libu2f-host#130]
When trying to use libu2f-host with the latest Windows 10 May 2019 Update (1903) it can't seem to find any U2F devices:

```
C:\libu2f-host-1.1.10-win64\bin>u2f-host -aregister -o https://demo.yubico.com < foo > bar
error: u2fh_devs_discover (-5): cannot find U2F device
```

However, when running in an elevated Command Prompt as Administrator it works fine.

**Comment by klali** [comment]
From the 1903 update Windows is blocking native access to fido devices and providing an API of their own for interacting. Please see https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/webauthnapis for additional detail.

**Comment by nevun** [comment]
We are archiving this project and closing issues. Please open a new one in the replacement library's repo: https://github.com/Yubico/libfido2 if it is still applicable.
