### ISSUE TITLE
ykman doesn't list Yubico Nano 4C/5C, but I can use it from Chrome

### ISSUE THREAD

**Issue by dandv** [Yubico/libu2f-host#131]
I'm running Ubuntu 18.04 and can use my Yubico 4C/5C (impossible to tell which I have by physically inspecting the key) with Chrome 74 to log into Gmail.

However, I can't see the key in the YubiKey Manager, or use it with any other sites in Chrome. I've followed the [Linux setup instructions](https://support.yubico.com/support/solutions/articles/15000006449-using-your-u2f-yubikey-with-linux), rebooted serveral times, started `pcscd.service` and `pcscd.socket` per the [Arch guide](https://wiki.archlinux.org/index.php/YubiKey), but `sudo ykman list` still shows nothing.

I got the key as part of a giveaway while I was a Google employee.

**Comment by klali** [comment]
Can you check what productId the device has using lsusb:

$ lsusb -d 1050:

**Comment by dandv** [comment]
Bus 001 Device 004: ID 1050:0200 Yubico.com U2F Gnubby

**Comment by klali** [comment]
That device is unfortunately not a YubiKey but a custom device made for google. It works for u2f but isn't a YubiKey in any other way.
