### ISSUE TITLE
Makefile for MacOS X could be improved

### ISSUE THREAD

**Issue by westfeld** [Yubico/libu2f-host#17]
I have taken a look at the Makefile used in MacOS X `macosx.mk` and it is very monolithic and uses one target only. This could be improved for easier understanding and to be able to use this makefile for development builds, too.

**Comment by JonnyWhatshisface** [comment]
I'm having issues on Mac OS X in general.... I can't get anything to build properly as far as the u2f goes. 

I've already installed libu2f-host via make -f macosx.mk VERSION=0.0.4 , which gives me working binaries in the u2f-host directory. However, there's no install that seems to take place.

Trying to run a configure on pam-u2f gawks that libu2f-host is not found, but trying to run an install on libu2f-host gawks that hidapi-hidraw isn't found...

Any input?

**Comment by cpcowart** [comment]
The OS X Makefile is not really a Makefile -- it may as well be included as a shell script.

There's also no need to have a separate OS X Makefile -- the Unix one works just fine.

Assuming you actually want to build HEAD on OS X, these instructions worked for me (OS X 10.10.5):
* Install homebrew (requires xcode -- you may get by with Fink or Macports too); these are pre-reqs for working with pretty much any open source project
* `$ brew install pkg-config`
* `$ brew install json-c`
* `$ brew install hidapi`
* `$ brew install libtool`
* `$ brew install gengetopt`
* `$ cd $WHEREEVER/libu2f-host`
* `$ autoreconf -i`
* `$ ./configure --prefix=/usr/local`
* `$ make`
* `$ make install`

NB: autoconf does NOT look for gengetopt -- I didn't notice it wasn't there until make barfed: 
    gengetopt --no-handle-help --input cmdline.ggo Makefile.am
    make[2]: gengetopt: No such file or directory
There should be an autoconf macro that checks for this. It would look something like:
    AC_CHECK_PROG([gengetopt],[gengetopt],[yes],[no])
    AM_CONDITIONAL([FOUND_GENGETOPT], [test "x$gengetopt" = xyes])
    AM_COND_IF([FOUND_GENGETOPT],,[AC_MSG_ERROR([required program 'gengetopt' not found.])])

**Comment by JonnyWhatshisface** [comment]
Thank you for the update. I will give this a try this evening.

**Comment by nevun** [comment]
We are archiving this project and closing issues. Please open a new one in the replacement library's repo: https://github.com/Yubico/libfido2 if it is still applicable.
