### ISSUE TITLE
Build on Mac OS X Fails

### ISSUE THREAD

**Issue by JonnyWhatshisface** [Yubico/libu2f-host#23]
make[2]: Nothing to be done for `check-am'.
cp: ../libu2f-host-0.0.tar.xz: No such file or directory
make: *** [doit] Error 1

...

**Comment by klali** [comment]
two things are required when using the macosx.mk or windows.mk first running make dist (or downloading a source tarball from https://developers.yubico.com/libu2f-host/Releases/) and then running the makefile with VERSION set to the version of the tarball, like:

 $ make -f macosx.mk VERSION=0.0.4

**Comment by JonnyWhatshisface** [comment]
I apologize once again for not updating this. I got it worked out... I thought, for whatever reason, that it was trying to download the tarball. :) I got it compiled properly... Thank you for the response, though.
