### ISSUE TITLE
Feature request - Add a Timeout 

### ISSUE THREAD

**Issue by azqa** [Yubico/libu2f-host#24]
After the command for registration or authentication is executed, the process waits for an infinite amount of time for the response from the key. There should be a timeout just like there is in the Javascript api.

**Comment by azqa** [comment]
No, it doesnt.

u2f-host.exe -aregister -o <my server here> < foo.txt

I execute the above command. It keeps on waiting for more than 5 minutes but never gives a timeout error.

**Comment by klali** [comment]
This was just added to the code, it will be in the next release which will be out soon.
