### ISSUE TITLE
Bug in Authentication Module

### ISSUE THREAD

**Issue by azqa** [Yubico/libu2f-host#26]
1-  Whenever I have more than two keys registered for an account, the library only authenticates the latest one and for all the other registered keys, I receive "Authentication error"

2- Whenever I have more than 2 keys registered, on authentication the library returns the following error and then quits: 
   "read: no error"

**Comment by klali** [comment]
I don't really understand what you're doing to get these errors, it'd help to see example code for how you're calling the library or how you're using the u2f-host binary to get these errors.

There are no functions in the library for doing authentication with more than one handle, u2fh_authenticate() accepts the server challenge for one device and tries that with all attached keys. Issue #10 talks about adding functions for working with more than one keyhandle but that's non-existant for now and anything like that has to be done in the calling application.
