### ISSUE TITLE
Feature request: Re-registration of keys

### ISSUE THREAD

**Issue by azqa** [Yubico/libu2f-host#27]
Currently, one key can be registered more than once for a given account. It should either provide an option (like the JS api does) to enable/disable re-registration of tokens, or if it does re-register, enable the developer to delete the previous entry from the database.

**Comment by nevun** [comment]
We are archiving this project and closing issues. Please open a new one in the replacement library's repo: https://github.com/Yubico/libfido2 if it is still applicable.
