### ISSUE TITLE
Support for others FIDO U2F tokens

### ISSUE THREAD

**Issue by mhalano** [Yubico/libu2f-host#29]
It is possible add support for others FIDO U2F keys in the 70-u2f.rules file? I think could be good if compatibility was improved. I have some USB vendor and product IDs which could be very useful if someone take care of this bug.

**Comment by klali** [comment]
Yes, I believe that would be good. We (Yubico) have not cared to hunt down other vendor and product ids, but if it's submitted as a pull request I'll be happy to merge it.

**Comment by mhalano** [comment]
I submitted a pull request. Please let me know if pull request is fine. I rarely done pull requests.
