### ISSUE TITLE
Requesting an exportable function, equivalent of "free", for data returned in response to u2fh_register/authenticate functions

### ISSUE THREAD

**Issue by marianpascalau** [Yubico/libu2f-host#41]
Hi there,
Is there a reason why there is no function exported by your shared library to free the results allocated by u2fh_register and u2fh_authenticate functions? 

As example, I have managed to compile this program for Windows, I have written a DLL Wrapper, but I have no equivalent in .Net to release the responses in managed code (malloc/strdup pointers) . In Windows there is an API to allocate special buffers but your library is using only C-runtime calls.

Is it possible that you make the "free" function exportable or change the way you allocate these pointers? 

My proposal is to add an extra exportable function:
void u2fh_free_data(void* data) {
    free(data);
}

**Comment by klali** [comment]
I'm thinking that it would make more sense to provide (new) functions where you pass in already allocated buffers to be filled rather than giving out allocated memory.. opinions?

**Comment by marianpascalau** [comment]
Hi, of course, 
I have no Problem with your proposal. My solution is only quick to implement, your solution is better.
The function u2fh_get_device_description works actually exactly as you suggested. The Problem is that a solution is needed ASAP, the test sample provided with this Project produce Memory leaks (the response is simply not deleted).

What would be to me really useful (as Feature) is the support for TCHARs (Unicode).

**Comment by marianpascalau** [comment]
Hi klali , thank you for the Change. 
Although the Change solves the Problem with the Memory buffers there is a new Problem now. 

Let's assume that the user is now allocating a smaller buffer and Triggers a Registration (or Authentication) request. The user push the button on the U2F device and the program will return an error because the buffer is too small. 

All OK, but now when I reallocate a larger buffer and I remake the last call I have to push once more the button (the original Response is not available anymore). This is not actually a proper behaviour and this force me allocate a much larger buffer by default.

The same for SendAndReceive. Because of that, I will personally rather preffer the original Interface with a new "export" function to free the buffer by the "shared-library" itself.
