### ISSUE TITLE
u2fh_devs_discover does not detect plug-up security key

### ISSUE THREAD

**Issue by Chaz6** [Yubico/libu2f-host#42]
dmesg shows:-

[3739895.606335] hid-generic 0003:2581:F1D0.0002: hiddev0,hidraw0: USB HID v1.01 Device [Plug-up Plug-up] on usb-0000:00:1a.1-1/input0

however when running pamu2fcfg it is not detected (No device found. Aborting.) The page for this key is http://www.pu1.fr/sk

**Comment by klali** [comment]
udev rules for plugup (among others) where added after the latest release, this is probably the cause of your error. You can try to take the file 70-u2f.rules from the git repository and replace the one you have installed.

**Comment by Chaz6** [comment]
Thank you for your help.
