### ISSUE TITLE
Resolve differences of header files with latest FIDO draft

### ISSUE THREAD

**Issue by agoode** [Yubico/libu2f-host#43]
The header files u2f.h and u2f_hid.h are different from the master copies at https://fidoalliance.org/specs/u2f-specs-master/inc/.

There are non-trivial changes to each of these files, including changes of constants like `U2F_SW_WRONG_DATA` and `U2F_VENDOR_FIRST`. But there are also just missing constants like `U2F_CHECK_REGISTER`.

`U2FHID_SYNC` also seems missing.

Even if the two versions of files differ, I would not expect them to be incompatible as they currently are. It is possible that the FIDO draft files would need an update as well.

**Comment by larsonmpdx** [comment]
It's worse than this - there are internally defined constants or magic
numbers sprinkled throughout the code when things are available in fido
headers.  For example, register.c uses V2CHALLEN + HOSIZE (internally
defined) when it should use U2F_CHAL_SIZE + U2F_APPID_SIZE (u2f.h)

I recently did a rewrite to simplify the code for my use and remove posix
dependencies - I'll be releasing within the next month or so.  I don't
remember it being a big deal to use the new headers.  You can probably fix
most everything by just replacing the headers and seeing what breaks, it
should be just renames.

**Comment by klali** [comment]
I am not convinced that what can be found under the directory u2f-specs-master should be used as an input for anything (especially not those header files). As you say they mention the command U2F_CHECK_REGISTER which is not to be found in the specs at all.

I think this needs more thought than just grabbing the header from that folder.

As for other constants being used incorrectly, please submit a pull request.

**Comment by nevun** [comment]
We are archiving this project and closing issues. Please open a new one in the replacement library's repo: https://github.com/Yubico/libfido2 if it is still applicable.
