### ISSUE TITLE
Documentation: libhidapi-dev required

### ISSUE THREAD

**Issue by candlerb** [Yubico/libu2f-host#48]
At <https://developers.yubico.com/libu2f-host/#_building> it says:

~~~
apt-get install pkg-config libjson0-dev libhidapi-hidraw0
~~~

But actually you need libhidapi-dev as well. Otherwise you get the following error at configure time:

~~~
checking for HIDAPI... no
checking for HIDAPI... no
configure: error: Package requirements (hidapi-hidraw) were not met:

No package 'hidapi-hidraw' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables HIDAPI_CFLAGS
and HIDAPI_LIBS to avoid the need to call pkg-config.
~~~

**Comment by a-dma** [comment]
Are you trying to build sources or a release tarball?

They required different procedures. The requirements for libhidapi-dev is mentioned a few lines below in https://developers.yubico.com/libu2f-host/#_building_from_git.

**Comment by candlerb** [comment]
I am building a release tarball: `libu2f-host-1.1.0.tar.xz` under Ubuntu 14.04

**Comment by a-dma** [comment]
Sorry, you're right. I checked this too hastily.
We'll update the documentation. Thanks for pointing it out.
