### ISSUE TITLE
Inconsistent URL scheme restrictions

### ISSUE THREAD

**Issue by candlerb** [Yubico/libu2f-host#49]
pamu2fcfg lets you use arbitrary URL schemes:

~~~
pamu2fcfg -o ssh:// -i ssh:// -u brian
~~~

The pam_u2f module happily accepts these arbitrary URL schemes:

~~~
auth sufficient pam_u2f.so debug manual origin=ssh://
~~~

And it generates challenges for them:

~~~
Now please copy-paste the below challenge(s) to 'u2f-host -aauthenticate -o ssh://'
{ "keyHandle": "veLxrf9NWAI_Y5-0dfAkp3UiIknKJPtNJ8vKLhQGitg7QhyHDA6kFHY6-mio0qpPtttHOGmJWGtvQ5cuOjmw9A", "version": "U2F_V2", "challenge": "StYAl-MqRhJiic9ftRGRzwNnkcA1p6cteCkB-7mvXE0", "appId": "ssh:\/\/" }
Now, please enter the response(s) below, one per line.
[0]:
~~~

But u2f-host doesn't permit them:

~~~
$ u2f-host -aauthenticate -o ssh://
error: origin must be pam, http or https
~~~

(aside: it also doesn't validate the origin scheme until after stdin is closed, whereas it could do immediately)

So this appears to be inconsistent. Either u2f-host should allow arbitrary schemes; or pamu2fcfg / pam_u2f should enforce the same limitations.

I'm filing this against libu2f-host because I don't see a particular reason in the U2F documentation to limit origins to those three schemes, nor can I find any official documentation of the `pam` scheme.

I can find [examples of app IDs](https://fidoalliance.org/specs/fido-u2f-v1.0-nfc-bt-amendment-20150514/fido-appid-and-facets.html) with `apk:` and `ios:` schemes.

**Comment by klali** [comment]
Good point, lets drop that code.
