### ISSUE TITLE
Build fails on Mac OS 10.10.5

### ISSUE THREAD

**Issue by garrettr** [Yubico/libu2f-host#50]
[Output](https://gist.github.com/garrettr/387a7f437610707db1d4) of `make -f macosx.mk VERSION=0.0` (it's long and has a lot of long lines, so I thought a Gist might be easier to read).

**Comment by klali** [comment]
This build could use more documentation. Essentially it needs a dist tarball (either from https://developers.yubico.com/libu2f-host/Releases/ or one you make yourself with make dist) in the current directory and the VERSION parameter should match the version of that tarball.

**Comment by garrettr** [comment]
@klali Thanks for clarifying the documentation!

**Comment by garrettr** [comment]
> or one you make yourself with make dist

How does that work?

**Comment by a-dma** [comment]
You can create it with `make dist`, but the build system will barf at you if you don't have gtk-doc installed and enabled.

run `./configure --enable-gtk-doc && make dist`
