### ISSUE TITLE
hid_transport list_devices() method only returns the class name instead of an actual device object

### ISSUE THREAD

**Issue by stigbosmans** [Yubico/libu2f-host#52]
On line 71 in hid_transport.py only the following line is implemented:
`devices.append(HIDDevice)`
whereas I would expect that an object of the class HIDDevice would be implemented, like below:
`devices.append(HIDDevice(d['path']))`

Is there another way to obtain a list of actual HIDDevice objects? Or am I doing something wrong?

**Comment by klali** [comment]
I'm guessing this should be an issue on https://github.com/Yubico/python-u2flib-host ?

**Comment by stigbosmans** [comment]
Correct, my bad. Thanks for your response, I will close this here.
