### ISSUE TITLE
try to get udev rules into systemd

### ISSUE THREAD

**Issue by wt** [Yubico/libu2f-host#53]
It would be great if the udev rules could be pushed into upstream systemd so that they would just be on systems by default. I think the following location is where they go:
https://github.com/systemd/systemd/tree/master/rules

**Comment by klali** [comment]
the debian package for systemd apparently includes parts of the rules now: http://anonscm.debian.org/cgit/pkg-systemd/systemd.git/commit/?id=09b5bcb064836aa5bae7484e1f1d5064c7aeb2e4

**Comment by Rondom** [comment]
See systemd/systemd#102 for an earlier attempt.

**Comment by wt** [comment]
Was this ever added to systemd? It doesn't look like it.

**Comment by nbraud** [comment]
@wt No; the systemd upstream rejected inclusion in their tree, and the Debian systemd maintainers removed the extra rules (this was a temporary measure, as there was no consensus on how to proceed by the time of the Stretch release).

The consensus, in Debian, is to have a [`libu2f-udev` package](https://bugs.debian.org/846359) (built from `libu2f-host`, so we don't have to maintain it separately), and have it [installed on desktop systems](https://bugs.debian.org/891472) and [installed by relevant applications](https://bugs.debian.org/891473).

I'm considering packaging [u2f-hidraw-policy](https://github.com/amluto/u2f-hidraw-policy/), which has a much more generic way of handling this (but having even more privileged C code exposed to USB devices doesn't fill me with warm fuzzy feelings)

**Comment by nickray** [comment]
@nbraud that would be great to merge u2f-hidraw-policy into udev, and upstream seems willing to accept: https://github.com/systemd/systemd/issues/11996

**Comment by nbraud** [comment]
@nickray Interesting, thanks for the info.

**Comment by FabianHenneke** [comment]
`u2f-hidraw-policy` has been integrated into systemd now: https://github.com/systemd/systemd/issues/11996.

**Comment by nevun** [comment]
We are archiving this project and closing issues. Please open a new one in the replacement library's repo: https://github.com/Yubico/libfido2 if it is still applicable.
