### ISSUE TITLE
Split packages by license: LGPLv2 vs. GPLv3

### ISSUE THREAD

**Issue by dripton** [Yubico/libu2f-host#55]
It's great that parts of the libu2f-host package are now LGPLv2 licensed.  However, other parts are still GPLv3, and the only way to tell which is which is checking the license headers in individual source files.  Having a package with per-file licensing is very confusing and error-prone.

The ideal solution would be splitting into two packages, each with a single license.  Then organizations that cannot use GPLv3 code could import the LGPLv2 code with no fear of accidentally using the wrong file and causing legal problems.

**Comment by klali** [comment]
I think this makes good points. Our current thinking is to re-license everything to LGPLv2 but we have some internal hoops to jump through to get there.

**Comment by dripton** [comment]
Relicensing everything to LGPLv2 would be awesome too.  Thanks for considering it.

**Comment by klali** [comment]
one problem here are the files maint.mk and GNUmakefile that seem to be under GPL not LGPL.. will have to look deeper into that..

**Comment by lfaraone** [comment]
@klali: in general, e.g. Debian does not consider the build system "a part of" the package, in any case, the build system is not included in the output of the build. So I think it would be helpful to clarify that the project is LGPLv2.1+ as a whole, to avoid confusion.
