### ISSUE TITLE
libu2f-host Ubuntu build issues

### ISSUE THREAD

**Issue by michaelcress** [Yubico/libu2f-host#58]
Following the "Building from Git" instructions on the libu2f-host main project page yielded errors for me. Solving them was a matter of apt-get installing the following:

dblatex

Should these packages be added to the "apt-get install gtk-doc-tools gengetopt help2man" build instruction?

**Comment by mikecress** [comment]
Disregard this issue. I somehow overlooked the Dependencies section on this page.

**Comment by a-dma** [comment]
You shouldn't need to install `dblatex` as far as I can see it's only a recommended/suggested dependency.
Typically recommended dependencies are installed automatically.
