### ISSUE TITLE
libu2f-host.so.0 not found after build

### ISSUE THREAD

**Issue by mikecress** [Yubico/libu2f-host#59]
My system was initially not able to find the libu2f-host.so.0 file after building. Below is an output message for u2f-host:

u2f-host: error while loading shared libraries: libu2f-host.so.0: cannot open shared object file: No such file or directory

The issue can be resolved by updating LD_LIBRARY_PATH as follows:
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib

Can this be added to the main project page?

**Comment by a-dma** [comment]
Are you building from source? Do you have (a fairly recent version of) libtool installed?

**Comment by mikecress** [comment]
I checked out the code from Git, installed the dependencies, and did the typical configure..make...make install sequence successfully. I didn't think to log out and back in again (to refresh any env variables) but it seems to be working fine for me now without having to set the LD_LIBRARY_PATH explicitly. Not really sure what the issue was but I'm going to close this.
