### ISSUE TITLE
build error for windows

### ISSUE THREAD

**Issue by training-harshad10** [Yubico/libu2f-host#63]
I am trying to build for windows using my Ubuntu VM. I have cloned project on Ubuntu 14.04 deployed on VM. When building, it throws error /usr/bin/ld: unrecognized option '--enable-auto-image-base'. Am I missing something? Downloaded tarball from https://developers.yubico.com/libu2f-host/Releases/ for version 1.1.2.

**Comment by klali** [comment]
This should build fine like that. The windows.mk provided should help in doing the build. You can execute it like:
 $ make -f windows.mk 32bit VERSION=1.1.2

Required dependencies for this are wine, mingw-w64 and mingw-w64-dev

Does that help?

**Comment by training-harshad10** [comment]
Yeah this worked fine! Thanks for help. Just wondering whether all those packages are required to build or some of them & whether it was just my case or those packages are needed for build on every ubuntu system as documents don't describe them.
