### ISSUE TITLE
Modify libu2f-host license to BSD compatible

### ISSUE THREAD

**Issue by fxkai** [Yubico/libu2f-host#78]
Is there a possibility to release an BSD compatible licensed version of the libu2f-host library?

This would help a lot bringing forward a native openSSH support (see https://bugzilla.mindrot.org/show_bug.cgi?id=2319)

**Comment by klali** [comment]
Since this project uses dependencies from gnulib changing the license is not possible without at least doing work to change that.

**Comment by emaste** [comment]
If someone does the work to remove the dependencies would the license be changed?

**Comment by martelletto** [comment]
On 08/06/2019 11:11, Ed Maste wrote:
> If someone does the work to remove the dependencies would the license be changed?

Yubico has a re-implementation of libu2f-host with FIDO2 support under a
BSD license: https://github.com/yubico/libfido2

-p.

**Comment by emaste** [comment]
Ah, thanks for the link.

**Comment by nevun** [comment]
Seems this has been resolved since we now have native FIDO2 support in OpenSSH with libfido2.
