### ISSUE TITLE
documentation: replace tmpl files

### ISSUE THREAD

**Issue by eworm-de** [Yubico/libu2f-host#84]
The gtk-doc project finally [removed the support for tmpl files](https://git.gnome.org/browse/gtk-doc/commit/?id=46df4354abed5724697fd5e39630c5bbc6637cc4), so currently the build fails with missing `gtkdoc-mktmpl`. Please update the documentation with something actively supported.

**Comment by nevun** [comment]
We are archiving this project and closing issues. Please open a new one in the replacement library's repo: https://github.com/Yubico/libfido2 if it is still applicable.
