### ISSUE TITLE
error (-3): error in JSON handling

### ISSUE THREAD

**Issue by JensC** [Yubico/libu2f-host#87]
Hi guys,
This is probably a noob error. I got libu2f-host compiled for OSX as well as for a Raspi and I am using a localhost u2f-server (python). Register a challenge works fine. The foo file contains some json data, but the next step

u2f-host -aregister -o http://localhost:8081 < foo > bar

fails with: error (-3): error in JSON handling for OSX as well for Raspbian.
Any idea whats wrong with that?

Thanks in advance
Jens

**Comment by nevun** [comment]
We are archiving this project and closing issues. Please open a new one in the replacement library's repo: https://github.com/Yubico/libfido2 if it is still applicable.
