### ISSUE TITLE
Please simplify unlocking U2F on Linux

### ISSUE THREAD

**Issue by dandv** [Yubico/libu2f-host#88]
https://www.yubico.com/support/knowledge-base/categories/articles/can-set-linux-system-use-u2f/ advises

> If you have a YubiKey NEO or YubiKey NEO-n ensure you have unlocked the U2F mode by following the instructions at http://yubi.co/unlockU2F

[That link](http://yubi.co/unlockU2F) redirects to a PDF that says to "Build the YubiKey NEO Manager application on a Linux distro", but https://developers.yubico.com/yubikey-neo-manager/ says the Manager is deprecated.

**Comment by nbraud** [comment]
@dandv I'm not with Yubico, but I'm pretty sure you want [`yubikey-manager`], which I packaged in Debian and should be part of the next release.
Moreover, you will need udev rules that allow you to access the device as a non-`root` user; they are packaged in this repository, and available under the name `libu2f-udev` on Debian (though they should be installed by default).

[`yubikey-manager`]: https://github.com/Yubico/yubikey-manager/
