### ISSUE TITLE
Make the udev rules work without systemd

### ISSUE THREAD

**Issue by nbraud** [Yubico/libu2f-host#96]
It has been pointed out on the [Debian BTS](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=892779) that the rules we are currently shipping do not work without `systemd-logind` (as `uaccess` requires that).

Would there be any drawbacks to making the devices accessible to group `plugdev` on top of having the `uaccess` tag?

**Comment by nbraud** [comment]
Ping?  FYI, `android-sdk-platform-tools-common` does the exact same thing to make Android debug interfaces available in both systemd and SysV environments.

**Comment by a-dma** [comment]
I don't think this would be problematic. @klali ?
